name: Feature Request
description: Haben Sie einen Feature Wunsch für VARIOS AI?
labels: 
  - "feature"
  - "new"
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank, dass Sie sich die Zeit genommen haben, Ihren Wunsch einzureichen.
  - type: textarea
    id: description
    attributes:
      label: Bezieht sich Ihre Feature Anfrage auf ein Problem? Bitte beschreiben Sie es.
      placeholder: "Eine klare und prägnante Beschreibung des Problems. Beispiel: Ich bin immer frustriert, wenn [...]"
    validations:
      required: true
    
  - type: textarea
    id: solution
    attributes:
      label: Beschreiben Sie die Lösung, die Sie sich wünschen
      placeholder: Eine klare und prägnante Beschreibung dessen, was Sie wollen.

  - type: textarea
    id: alternate
    attributes:
      label: Beschreiben Sie die Alternativen, die Sie in Betracht gezogen haben
      placeholder: Eine klare und prägnante Beschreibung aller alternativen Lösungen oder Funktionen, die Sie in Betracht gezogen haben.

  - type: textarea
    id: context
    attributes:
      label: Zusätzlicher Kontext
      placeholder: Fügen Sie hier weitere Informationen oder Screenshots zu Ihrer Anfrage hinzu.
